### ISSUE TITLE
How to do localization of Synthea data to specific country

### ISSUE THREAD

**Issue by SUHASV117** [inferno-framework/uscore-data-script#21]
In the original Synthea repository there is an option to configure the Synthea data to other locations. Even the data for each specific country can be be found in Synthea-International repository. But, how can we add this localized data into Synthea output in uscore-data-script? Is there any option of doing this?

**Comment by jawalonoski** [comment]
You would have to manually apply the changes described in the Synthea-international README to the Synthea JAR file in the this repo. You'd have to unzip the JAR, apply the changes, and then repackage the JAR. You might have to modify the script command that executes Synthea to specify the location it should create data for since the default location (Massachusetts) will no longer exist after you apply international configurations.

https://github.com/inferno-framework/uscore-data-script/blob/master/lib/synthea/synthea.jar

https://github.com/synthetichealth/synthea-international#readme
